#title: SDG Ukraine (STG)

#remote_theme: open-sdg/open-sdg

#plugins:
#  - jekyll-remote-theme
#  - jekyll-open-sdg-plugins

#markdown: kramdown


title: Ukraine SDG (Staging)
baseurl: ""
url: ""

theme: null
remote_theme: open-sdg/open-sdg@2.4.1

plugins:
  - jekyll-open-sdg-plugins
  - jekyll-remote-theme

exclude:
  - vendor
  - node_modules
