#title: SDG Ukraine (STG)

#remote_theme: open-sdg/open-sdg

#plugins:
#  - jekyll-remote-theme
#  - jekyll-open-sdg-plugins

#markdown: kramdown


theme: open-sdg/open-sdg
plugins:
  - jekyll-open-sdg-plugins
