environment: staging
# Replace my-github-org and open-sdg-data-starter as needed.
remote_data_prefix: "https://sdg-kitsoft-stg.github.io/data-ukraine-sdg"
analytics:
  # For production, you likely want to enter a Google Analytics code below.
  ga_prod: ''

languages:
  - en
  - ua
  - uk